# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('breed', models.CharField(max_length=128)),
                ('size', models.CharField(max_length=64)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(max_length=64)),
                ('weight', models.PositiveIntegerField()),
                ('rabies_date', models.DateField()),
                ('distemper_date', models.DateField()),
                ('parvo_date', models.DateField()),
                ('bordetello', models.DateField()),
                ('notes', models.TextField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MWDTCClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=12)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('cell_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email_address', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.MWDTCClient'),
        ),
    ]
