# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0002_auto_20170824_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='client',
            name='home_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
