# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0003_auto_20170824_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='client_data.Client'),
        ),
    ]
