# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0005_dayrunreservation_reservation_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('classSize', models.PositiveSmallIntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('dayOfTheWeek', models.CharField(max_length=16)),
                ('enrolled', models.PositiveSmallIntegerField(default=0)),
                ('classIsOver', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DogStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.DogClass')),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.Client')),
                ('dogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.Dog')),
            ],
        ),
        migrations.AlterField(
            model_name='dayrunreservation',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
