# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0006_auto_20170827_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogclass',
            name='enrolled',
        ),
    ]
