# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0007_remove_dogclass_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogclass',
            name='enrolled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
