# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0008_dogclass_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='client_data.Dog'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dog2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='client_data.Dog'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='dog3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third', to='client_data.Dog'),
        ),
        migrations.AlterField(
            model_name='dogstudent',
            name='dogId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogstudent', to='client_data.Dog'),
        ),
        migrations.AlterField(
            model_name='run',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstRun', to='client_data.Dog'),
        ),
        migrations.AlterField(
            model_name='run',
            name='dog2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondRun', to='client_data.Dog'),
        ),
        migrations.AlterField(
            model_name='run',
            name='dog3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdRun', to='client_data.Dog'),
        ),
    ]
