# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0009_auto_20170828_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayRun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.DayRunReservation')),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.Reservation')),
            ],
        ),
        migrations.RemoveField(
            model_name='run',
            name='day',
        ),
        migrations.RemoveField(
            model_name='run',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='run',
            name='dog2',
        ),
        migrations.RemoveField(
            model_name='run',
            name='dog3',
        ),
        migrations.RemoveField(
            model_name='run',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
