# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0010_auto_20170828_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runreservation',
            name='dayRun',
        ),
        migrations.RemoveField(
            model_name='runreservation',
            name='res_id',
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res1', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res10', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res11', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res12', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res13', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res14', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res15', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res16', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res17', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res18', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res19', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res2', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res20', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res21', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res22', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res23', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res24', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res25', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res26', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res27', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res28', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res29', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res3', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res30', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res4', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res5', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res6', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res7', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res8', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res9', to='client_data.Reservation'),
        ),
        migrations.DeleteModel(
            name='RunReservation',
        ),
    ]
