# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0011_auto_20170828_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayrunreservation',
            name='available_runs',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
