# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0012_dayrunreservation_available_runs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayrunreservation',
            name='available_runs',
        ),
    ]
