# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0017_auto_20170830_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='check_date_report',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
