# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0018_dog_check_date_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='dayrunreservation',
            name='RunRes',
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='RunRes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RunRes', to='client_data.Reservation'),
        ),
        migrations.AddField(
            model_name='dogreservation',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayres', to='client_data.DayRunReservation'),
        ),
        migrations.AddField(
            model_name='dogreservation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foundres', to='client_data.Reservation'),
        ),
    ]
