# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0020_auto_20170830_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogreservation',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dogreservation',
            name='reservation',
        ),
        migrations.AddField(
            model_name='dayrunreservation',
            name='Res2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run2', to='client_data.Reservation'),
        ),
        migrations.DeleteModel(
            name='DogReservation',
        ),
    ]
