# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0021_auto_20170830_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogDayRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='dayrunreservation',
            name='Res2',
        ),
        migrations.AddField(
            model_name='dogdayres',
            name='dayRun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.DayRunReservation'),
        ),
        migrations.AddField(
            model_name='dogdayres',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.Reservation'),
        ),
    ]
