# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0023_remove_dayrunreservation_runres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogdayres',
            name='dayRun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='client_data.DayRunReservation'),
        ),
    ]
