# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0025_auto_20170831_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogclass',
            name='privateClass',
            field=models.BooleanField(default=False),
        ),
    ]
