# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0027_reservation_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogstudent',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
