# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0031_auto_20171002_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogstudent',
            name='approved',
        ),
    ]
