# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0033_auto_20171004_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='approved',
        ),
    ]
