# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0034_remove_reservation_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='bordetello',
            new_name='bordetella',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='distemper_date',
            new_name='fecal_date',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='parvo_date',
            new_name='parvo_distemper_date',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='weight',
        ),
        migrations.AddField(
            model_name='dog',
            name='feedingInstructions',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='PickUpTime',
            field=models.CharField(choices=[('before noon', 'BEFORE NOON'), ('after noon', 'AFTER NOON')], default='before noon', max_length=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='kennel_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
