# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0036_dog_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='feedingInstructions',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='medication',
        ),
        migrations.AddField(
            model_name='reservation',
            name='feedingInstructions',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='medicationInstructions',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bath',
            field=models.BooleanField(default=False),
        ),
    ]
