# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0038_auto_20171018_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bath_dog_size',
            field=models.CharField(choices=[('toy', 'TOY'), ('medium', 'MEDIUM'), ('large', 'LARGE'), ('extra large', 'EXTRA LARGE')], default='medium', max_length=12),
        ),
    ]
