# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_data', '0039_reservation_bath_dog_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDogClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('Boarding/Train', 'BOARDING/TRAIN'), ('Private', 'PRIVATE'), ('Protection', 'Protection')], default='Boarding/Train', max_length=16)),
                ('kennel_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sessions', models.PositiveSmallIntegerField(default=0)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('Bath', models.BooleanField(default=False)),
                ('nails', models.BooleanField(default=False)),
                ('bath_Date', models.DateField(blank=True, null=True)),
                ('follow_Up_Appointment', models.CharField(blank=True, max_length=32, null=True)),
                ('pick_up_time_and_date', models.CharField(blank=True, max_length=32, null=True)),
                ('feeding', models.TextField(blank=True, max_length=128, null=True)),
                ('Medication', models.TextField(blank=True, max_length=128, null=True)),
                ('Contanct_Phone', models.CharField(max_length=16)),
                ('Prong_Collar', models.BooleanField(default=False)),
                ('Treats', models.BooleanField(default=False)),
                ('Ecollar', models.BooleanField(default=False)),
                ('Extra_Boarding_days', models.CharField(blank=True, max_length=32, null=True)),
                ('Personal_Protection_Items', models.TextField(default='none', max_length=128)),
                ('Notes', models.TextField(default='none', max_length=128)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.DogClass')),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.Client')),
                ('dogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_data.Dog')),
            ],
        ),
    ]
